name: Docker Publish

on:
  push:
    paths:
      - "version.txt" # Trigger only if version.txt changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Read the version from version.txt
      - name: Read version
        id: version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      # Sometimes old or cached credentials can cause issues
      - name: Clear Docker config
        run: rm -f ~/.docker/config.json

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image with both tags
      - name: Build Docker image
        run: |
          docker build \
            --build-arg VERSION=$VERSION \
            -t ${{ secrets.DOCKER_USERNAME }}/webdav-daily-sync:$VERSION \
            -t ${{ secrets.DOCKER_USERNAME }}/webdav-daily-sync:latest .

      # Push both Docker image tags to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/webdav-daily-sync:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/webdav-daily-sync:latest
